### ISSUE TITLE
glib-object.h not found on OS X

### ISSUE THREAD

**Issue by dimitre** [arturoc/ofxNice#1]
I think it is just an addon_config.mk issue on OS X. 
And maybe it is the same issue reported here: https://forum.openframeworks.cc/t/ofxnice-build-example/19632/7
Thank you

**Comment by arturoc** [comment]
can you post the full error?

**Comment by dimitre** [comment]
Yes, in fact that is the full error. 

![screen shot 2017-05-02 at 7 16 34 pm](https://cloud.githubusercontent.com/assets/58289/25641693/e2d982f6-2f6b-11e7-82b7-92ebea20c68d.png)

**Comment by arturoc** [comment]
have you installed gstreamer? if not try following the instructions in ofxGStreamer and use that addon in your project too

**Comment by dimitre** [comment]
Thanks!
